# Generated by Django 4.2.7 on 2023-11-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_siom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='Usuario',
        ),
    ]
