# Generated by Django 4.2.7 on 2023-11-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siom', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('antibiotico', 'Antibiotico'), ('anti_inflamatorio', 'Anti Inflamatorio'), ('analgesico', 'Analgesico')], max_length=20)),
            ],
        ),
    ]
